name: keyword-releaser
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions.checkout@v3
      - uses: vikas-pawar-01/github-action-workflow@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'FIXED'
